# Generated by Django 2.2.7 on 2020-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
