# Generated by Django 2.1.4 on 2020-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20200316_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='own_partner_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Партнерский код'),
        ),
    ]
