# Generated by Django 2.1.4 on 2020-03-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20200302_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
