# Generated by Django 2.1.4 on 2020-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20200316_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner_balance',
            field=models.IntegerField(default=0, verbose_name='Партнерский баланс'),
        ),
    ]
