# Generated by Django 2.2.7 on 2020-03-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20200304_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='photo',
        ),
    ]
