# Generated by Django 2.2.7 on 2020-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_auto_20200304_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK аватар'),
        ),
    ]
