# Generated by Django 2.2.7 on 2020-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityAlias',
            field=models.CharField(max_length=30, null=True, verbose_name='Склонение города (должно отвечать на вопрос ГДЕ, например, Москве)'),
        ),
        migrations.AddField(
            model_name='city',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коэффициент стоимости размещения'),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тэг Description'),
        ),
        migrations.AddField(
            model_name='city',
            name='sub_domain',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Название поддомена(на пример msk)'),
        ),
        migrations.AddField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тэг Title'),
        ),
    ]
