# Generated by Django 2.1.4 on 2020-05-16 06:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticPage', '0002_auto_20200507_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст для главной страницы. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%')),
            ],
            options={
                'verbose_name': 'Текст на страницы',
                'verbose_name_plural': 'Тексты на страницы',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='title',
        ),
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Домен по умолчанию?'),
        ),
        migrations.AddField(
            model_name='pagetext',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometext', to='staticPage.City', verbose_name='Для поддомена'),
        ),
    ]
