# Generated by Django 2.1.4 on 2020-03-16 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0001_initial'),
        ('staticPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_apply', models.IntegerField(blank=True, null=True, verbose_name='Выбранная заявка')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('rent_time', models.IntegerField(null=True, verbose_name='Время аренды')),
                ('rent_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип аренды по времени')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Когда (дата)')),
                ('order_time', models.TimeField(blank=True, null=True, verbose_name='Когда (время)')),
                ('comment', models.TextField(null=True, verbose_name='Описание')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Проверена?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Учавстует в выдаче?')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Выполнена?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticPage.City', verbose_name='Местоположение')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSection', verbose_name='Относится к разделу')),
                ('sub_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSubSection', verbose_name='Относится к подразделу')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueType', verbose_name='Относится к типу')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка на технику',
                'verbose_name_plural': 'Заявки на технику',
            },
        ),
        migrations.CreateModel(
            name='TechniqueOrderApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Предложенная цена')),
                ('is_choosen', models.BooleanField(blank=True, default=False, verbose_name='Заказчик выбрал исполнителя?')),
                ('choose_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выбора исполнителем')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='Предложение принято?')),
                ('accept_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия предложения')),
                ('decline_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения предложения')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applys', to='techniqueOrder.TechniqueOrder', verbose_name='Относится к')),
                ('technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Предложенная техника')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Предложение от')),
            ],
            options={
                'verbose_name': 'Отклик на заявку',
                'verbose_name_plural': 'Отклики на заявки',
            },
        ),
        migrations.CreateModel(
            name='TechniqueOrderViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techniqueOrder.TechniqueOrder', verbose_name='Относится к')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Просмотренно пользователями')),
            ],
            options={
                'verbose_name': 'Заявка на технику',
                'verbose_name_plural': 'Заявки на технику',
            },
        ),
    ]
