# Generated by Django 2.1.4 on 2020-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniqueOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueorder',
            name='order_time',
            field=models.DateField(blank=True, null=True, verbose_name='Когда'),
        ),
    ]
