# Generated by Django 2.2.7 on 2020-03-10 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0005_auto_20200309_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techniqueOrder', '0002_techniqueorder_order_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniqueorder',
            options={'verbose_name': 'Заявка на технику', 'verbose_name_plural': 'Заявки на технику'},
        ),
        migrations.AlterField(
            model_name='techniqueorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда (дата)'),
        ),
        migrations.AlterField(
            model_name='techniqueorder',
            name='order_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Когда (время)'),
        ),
        migrations.CreateModel(
            name='TechniqueOrderViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techniqueOrder.TechniqueOrder', verbose_name='Относится к')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Просмотренно пользователями')),
            ],
            options={
                'verbose_name': 'Заявка на технику',
                'verbose_name_plural': 'Заявки на технику',
            },
        ),
        migrations.CreateModel(
            name='TechniqueOrderApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Предложенная цена')),
                ('is_choosen', models.BooleanField(blank=True, null=True, verbose_name='Заказчик выбрал исполнителем?')),
                ('choose_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выбора исполнителем')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='Предложение принято?')),
                ('accept_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия предложения')),
                ('decline_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения предложения')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techniqueOrder.TechniqueOrder', verbose_name='Относится к')),
                ('technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Предложенная техника')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Предложение от')),
            ],
            options={
                'verbose_name': 'Отклик на заявку',
                'verbose_name_plural': 'Отклики на заявки',
            },
        ),
    ]
