# Generated by Django 2.1.4 on 2020-03-16 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус платежа')),
                ('amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='payment/', verbose_name='Иконка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название платежа')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод платежа')),
            ],
            options={
                'verbose_name': 'Вид платежа',
                'verbose_name_plural': 'Виды платежей',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ya_payment.PaymentType', verbose_name='Вид платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
