# Generated by Django 2.1.4 on 2020-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
