# Generated by Django 2.1.4 on 2020-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_payment', '0002_auto_20200316_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobj',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачен?'),
        ),
    ]
