# Generated by Django 2.1.4 on 2020-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ya_payment', '0003_paymentobj_is_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentobj',
            name='amount',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Сумма платежа'),
        ),
    ]
