# Generated by Django 2.1.4 on 2020-04-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Отзыв')),
                ('rating', models.IntegerField(null=True, verbose_name='Оценка')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Отзыв о')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Отзыв')),
                ('rating', models.IntegerField(null=True, verbose_name='Оценка')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('about_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_user', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв о')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от')),
            ],
        ),
    ]
