# Generated by Django 2.1.4 on 2020-03-03 18:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название раздела техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название раздела)')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Верхний текст на страницу с услугой')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
            ],
            options={
                'verbose_name': 'Раздел техники',
                'verbose_name_plural': 'Разделы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название подраздела техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подраздела)')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Верхний текст на страницу с услугой')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
            ],
            options={
                'verbose_name': 'Подраздел техники',
                'verbose_name_plural': 'Подразделы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название типа техники')),
                ('image', models.ImageField(null=True, upload_to='technique/type/', verbose_name='Изображение (420 x 225)')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название типа)')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Верхний текст на страницу с услугой')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
            },
        ),
        migrations.AddField(
            model_name='techniquesubsection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueType', verbose_name='Относится к разделу'),
        ),
        migrations.AddField(
            model_name='techniquesection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueType', verbose_name='Относится к типу'),
        ),
    ]
