# Generated by Django 2.2.7 on 2020-03-05 09:14

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staticPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('min_rent_time', models.IntegerField(null=True, verbose_name='Минимальное время аренды')),
                ('rent_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип аренды по времени')),
                ('rent_price', models.IntegerField(null=True, verbose_name='Стоимость аренды')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('features', models.TextField(null=True, verbose_name='Характеристики')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Проверена?')),
                ('is_free', models.BooleanField(default=True, verbose_name='Статус свободен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticPage.City', verbose_name='Местоположение')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Еденицы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название раздела техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название раздела)')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
            ],
            options={
                'verbose_name': 'Раздел техники',
                'verbose_name_plural': 'Разделы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название типа техники')),
                ('image', models.ImageField(null=True, upload_to='technique/type/', verbose_name='Изображение (420 x 225)')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название типа)')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название подраздела техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подраздела)')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('seo_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте?')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSection', verbose_name='Относится к разделу')),
            ],
            options={
                'verbose_name': 'Подраздел техники',
                'verbose_name_plural': 'Подразделы техники',
            },
        ),
        migrations.AddField(
            model_name='techniquesection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueType', verbose_name='Относится к типу'),
        ),
        migrations.CreateModel(
            name='TechniqueItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='technique/items/', verbose_name='Изображение')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Изображение проверено?')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='technique.TechniqueItem', verbose_name='Изображение для')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueItemDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='technique/docs/', verbose_name='Документ')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Документ проверен?')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='technique.TechniqueItem', verbose_name='Документ для')),
            ],
        ),
        migrations.AddField(
            model_name='techniqueitem',
            name='sub_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSubSection', verbose_name='Относится к подразделу'),
        ),
    ]
