# Generated by Django 2.1.4 on 2020-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueitem',
            name='rate_times',
            field=models.IntegerField(default=0, verbose_name='РейтингT'),
        ),
    ]
