# Generated by Django 2.1.4 on 2020-03-03 18:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquesection',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название раздела)'),
        ),
        migrations.AlterField(
            model_name='techniquesection',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='techniquesection',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AlterField(
            model_name='techniquesection',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подраздела)'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSection', verbose_name='Относится к разделу'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название типа)'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотров категории'),
        ),
    ]
