# Generated by Django 2.2.7 on 2020-04-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniqueitemdoc',
            name='techniqueitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='technique.TechniqueItem', verbose_name='Документ для'),
        ),
    ]
