# Generated by Django 2.2.7 on 2020-04-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSubcribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueSection')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
