# Generated by Django 2.1.4 on 2020-03-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0002_auto_20200303_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techniquesubsection',
            old_name='type',
            new_name='section',
        ),
    ]
