# Generated by Django 2.2.7 on 2020-05-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0002_sectionsubcribes'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueitem',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AddField(
            model_name='techniquesection',
            name='base_price',
            field=models.IntegerField(blank=True, default=1000, verbose_name='Стоимость размещения'),
        ),
    ]
