# Generated by Django 2.1.4 on 2020-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0002_auto_20200305_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Учавстует в выдаче?'),
        ),
    ]
