# Generated by Django 2.2.7 on 2020-03-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0003_auto_20200303_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название техники')),
                ('name_lower', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Проверена?')),
                ('is_free', models.BooleanField(default=True, verbose_name='Статус свободен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticPage.City', verbose_name='Местоположение')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('sub_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technique.TechniqueSubSection', verbose_name='Относится к подразделу')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Еденицы техники',
            },
        ),
        migrations.CreateModel(
            name='TechniqueItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='technique/items/', verbose_name='Изображение')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Проверена?')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Изображение для')),
            ],
        ),
    ]
