# Generated by Django 2.1.4 on 2020-03-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0003_techniqueitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='techniquesection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='technique.TechniqueType', verbose_name='Относится к типу'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='technique.TechniqueSection', verbose_name='Относится к разделу'),
        ),
    ]
