# Generated by Django 2.1.4 on 2020-05-16 06:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0004_auto_20200507_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquesection',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название раздела) Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='techniquesection',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название подраздела) Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1 (если не указан, выводится название типа) Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО текст на страницу. Для вставки города используйте выражение %TOWN%, для склонения города %TOWN_ALIAS%'),
        ),
    ]
