# Generated by Django 2.1.4 on 2020-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0005_auto_20200516_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquesection',
            name='page_keywords',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='techniquesubsection',
            name='page_keywords',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='techniquetype',
            name='page_keywords',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Keywords SEO'),
        ),
    ]
