# Generated by Django 2.1.4 on 2020-03-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technique', '0005_auto_20200309_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNewMessages', models.BooleanField(default=False, verbose_name='Есть новые сообщения')),
                ('lastMessageOwn', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastMsgBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от')),
                ('techniqueitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Тема чата')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='chatusers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('isUnread', models.BooleanField(default=True, verbose_name='Не прочитанное сообщение')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat', verbose_name='В чате')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от')),
            ],
        ),
    ]
