# Generated by Django 2.1.4 on 2020-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
