# Generated by Django 2.1.4 on 2020-04-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('technique', '0001_initial'),
        ('techniqueOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от'),
        ),
        migrations.AddField(
            model_name='chat',
            name='lastMsgBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщение от'),
        ),
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techniqueOrder.TechniqueOrder', verbose_name='Тема чата заявка'),
        ),
        migrations.AddField(
            model_name='chat',
            name='techniqueitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technique.TechniqueItem', verbose_name='Тема чата техника'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chatusers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
