# Generated by Django 2.2.7 on 2020-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Полное название тарифа')),
                ('short_name', models.CharField(max_length=255, null=True, verbose_name='Сокращенное название тарифа')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('technique_count', models.IntegerField(default=0, verbose_name='Размещение техники в любой категории')),
                ('other_count', models.IntegerField(default=0, verbose_name='Размещение техники в категории Строительный инструмент ')),
                ('new_orders_delay', models.IntegerField(default=0, verbose_name='Задержка оповещения о новых заявках')),
                ('work_section', models.BooleanField(default=False, verbose_name='Доступ к разделу Работа')),
                ('work_notify', models.BooleanField(default=False, verbose_name='Получение уведомлений о новых предложениях работы')),
                ('can_see_phone', models.BooleanField(default=False, verbose_name='Возможность видеть нормер телефона')),
                ('can_call', models.BooleanField(default=False, verbose_name='Возможность позвонить Работодателю')),
                ('can_chat', models.BooleanField(default=False, verbose_name='Возможность написать Работодателю')),
                ('parter_bonus', models.IntegerField(default=0, verbose_name='Вознаграждение по партнерской программе %')),
                ('is_default', models.BooleanField(default=False, verbose_name='Тариф по умолчанию?')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
