# Generated by Django 2.1.4 on 2020-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='can_see_phone',
            field=models.BooleanField(default=False, verbose_name='Возможность видеть нормер телефона'),
        ),
    ]
