# Generated by Django 2.1.4 on 2020-03-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParnterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код партнера')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Код пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Начислено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.ParnterCode', verbose_name='Код')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
            ],
        ),
    ]
