# Generated by Django 2.1.4 on 2020-03-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customuser', '0003_auto_20200316_1225'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parnter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_partner', to=settings.AUTH_USER_MODEL, verbose_name='Код пользователя')),
            ],
        ),
        migrations.RemoveField(
            model_name='parntercode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='partnermoney',
            name='code',
        ),
        migrations.RemoveField(
            model_name='partnermoney',
            name='from_user',
        ),
        migrations.AddField(
            model_name='partnermoney',
            name='action',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Операция'),
        ),
        migrations.DeleteModel(
            name='ParnterCode',
        ),
        migrations.AddField(
            model_name='partnermoney',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Parnter', verbose_name='Партнер'),
        ),
    ]
